### PR TITLE
improve German translation

### PR DESCRIPTION
**Pull request by tiltX**
I have made fixes to the German translations. Since I don't have the means to build djv myself, I couldn't test it in action. I guess there are probably a few bits that need tweaking in the future (for example "none" can mean multiple things and take multiple suffixes in German, depending on the context).

I have kept a few English terms that are loaned words in German and familiar to people working in VFX and video (shortcut, thumbnail, tooltip, ...)

### CODE REVIEW

**Comment by darbyjohnston** [comment]
Hi, thanks for your help with the translations!  I merged the changes and will include this with the next release. I tried it out and everything worked fine technically. Would you like to be included on the credits page (https://darbyjohnston.github.io/DJV/credits.html) for helping out?

**Comment by tiltX** [comment]
thanks, that would be cool.

**Comment by darbyjohnston** [comment]
Great, just wanted to double-check, should the credit be for "tiltX"?

**Comment by tiltX** [comment]
please use "Stefan Ihringer"

**Pull request merged**
