### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by PiOverFour**
Hi, this updated translation isn’t perfect, but it makes the program usable.

I replaced the \u codes by the actual encoding, and it is recognised fine by DJV. Is that a problem? 

I made a couple of corrections in the English text as well.

(What’s up with all the fish stuff in djvCore?!)

### CODE REVIEW

**Comment by darbyjohnston** [comment]
Thanks for the updates! I'm not sure about the encodings, let's try it out and see how it works. It certainly makes the .text files more readable. Would you like to be added to the credits page for helping out with the translations?
https://darbyjohnston.github.io/DJV/credits.html

> (What’s up with all the fish stuff in djvCore?!)

It's a list of all the fish species in California. :) I just use it for testing where strings are needed, it should probably be removed from the translations...
http://calfish.ucdavis.edu/species/

**Comment by PiOverFour** [comment]
I wouldn’t mind being added to the credits.

> I just use it for testing where strings are needed, it should probably be removed from the translations...

Ha ha, I figured it wasn’t to be displayed in the UI! I didn’t bother correcting them, and I don’t think any translator would, so they’re not that much of a problem for translators.
The descriptions [appear to be](https://pisces.ucdavis.edu/doc/setup/license.html#license) under a [CC-BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/3.0/)-like license though, so it may be wise to remove them eventually, since the copyleft makes them incompatible with the 3-clause BSD license.

**Comment by darbyjohnston** [comment]
> I wouldn’t mind being added to the credits.

Great, as "PiOverFour"?

> The descriptions appear to be under a CC-BY-NC-SA-like license though, so it may be wise to remove them eventually, since the copyleft makes them incompatible with the 3-clause BSD license.

Oh, good catch! I should have checked that. I'll replace them with some public domain text.

**Comment by darbyjohnston** [comment]
OK, I replaced the descriptions with some public domain text. I also kept the list of fish as part of the translations since it can be useful for testing even if the machine translations aren't correct.

**Comment by PiOverFour** [comment]
> Great, as "PiOverFour"?
Rather as my name, which appears in the git commits :) Thanks.

**Pull request merged**
