### PR TITLE
Switch to using version 2.5.1 of openexr tree

### PR DESCRIPTION
**Pull request by kdt3rd**
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>

### CODE REVIEW

**Comment by kdt3rd** [comment]
So I test this under linux and seems to work fine. I was having issues with your provided FindIlmBase and FindOpenEXR cmake finders, given that now OpenEXR is using "modern" cmake and generating the cmake module thingie that find_package looks for. So I just deleted them and set the -DOPENEXR_FOUND manually. This method also does not seem to do the upper case on the module name in the _FOUND check, so it's OpenEXR_FOUND...

**Comment by darbyjohnston** [comment]
Great, nice work! I was able to successfully build locally on Windows and macOS plus all of the Azure builds went through, so it looks like everything is working except for the Travis build. I'll merge these changes and do some troubleshooting on that.

> So I just deleted them and set the -DOPENEXR_FOUND manually
That's great, I'm happy to use the ones directly from OpenEXR.

> But if other places rely on Half, we may need to add IlmBase::Half as a link requirement?
In the past I had things split up so that some code only linked to IlmBase, but I'm fine now with just linking everything to IlmImf. Since my local builds and the Azure builds were OK I think the link errors are something specific to Travis which I can investigate.

I'll merge this change and include it with the next release; would you like to be added to the credits page for your contribution?
https://darbyjohnston.github.io/DJV/credits.html

**Comment by darbyjohnston** [comment]
Oops, there was one last place I was relying on linking to IlmBase without IlmImf, that was for a "tiny" build (-DDJV_BUILD_TINY=TRUE), which is a stripped down build with as few dependencies as possible. Mostly just used for Travis to keep the build time within the ~1 hour limit. I added the "IlmBase::Imath" and "IlmBase::IlmThread" link targets to djvAV and everything builds OK now.

**Comment by kdt3rd** [comment]
if you want to give credit, that's fine, but I don't think it was a particularly exotic change, so don't worry about it too much. I should have mentioned that yes, there will be the IlmBase::Imath / Half / IlmThread targets... thanks for including the fix!

**Comment by darbyjohnston** [comment]
It's no worry at all, I appreciate the change especially since it simplified the code base by removing the custom FindIlmBase and FindOpenEXR files. Also thanks for the "Signed-off-by" comment! That reminds me that I need to adopt that convention for the project.

**Pull request merged**
