### PR TITLE
I18n: fix duplicates

### PR DESCRIPTION
**Pull request by PiOverFour**
Hi, so following up to #203, I fixed and renamed a lot of strings which were either badly named still, or which needed to be duplicated.

I was hoping not to break too much, but it appears some strings are broken, and I couldn’t find why. The ones I found are:
- `render_filter_[linear|nearest]`, in Settings → Render 2D. I have no idea why the language strings aren’t loaded;
- `widget_color_space_[config|display|image]` from the Color Space widget. Same thing, they _should_ load.

There may be others. I wonder if this string refactoring revealed a hidden bug, or if I did something stupid.

I didn’t use the translate script, so the new IDs exist only in the English version for now.
The English files are now sorted in (almost) alphabetical order.
There are probably old strings remaining, I don’t know if they should be removed…

### CODE REVIEW

**Comment by PiOverFour** [comment]
I looked around and saw 3 other strings showing the ID instead of the text: `playback_custom_playback_speed`, `playback_reset_speed`, `playback_play_every_frame`. Also, the first two have generic tooltips.

I can confirm that none of those strings were translated before, they directly used the IDs.

**Comment by darbyjohnston** [comment]
Hi, sorry for the delay, I'll take a look at the "render_filter_" string and see if I can figure out what's going on.

> There are probably old strings remaining, I don’t know if they should be removed…
Do you mean strings that are not used in the code anymore? It's probably fine to leave them for now, I can see periodically going through the strings and doing bits of cleanup.

**Comment by darbyjohnston** [comment]
Hi, I took a look and the missing string bugs are my fault, the C++ code where those are being used doesn't have the function to replace the ID with the actual text/translation. I can fix those up after these changes are merged.

**Comment by PiOverFour** [comment]
I didn’t succeed in bringing back the translations to the new keys. So, many of the translated strings are broken… Maybe they’d just as soon be translated again from the new IDs? I don’t mind going over the French version once more, it needs it anyway. Were there other corrected languages?
Apart from that I think the patch is good.

> Hi, sorry for the delay,

Oh, one day isn’t too long a delay! I’m not in a hurry, and I don’t feel entitled to press open source developers who may have other stuff to deal with. :)

> Do you mean strings that are not used in the code anymore? It's probably fine to leave them for now, I can see periodically going through the strings and doing bits of cleanup.

Yes, those. All right, thanks!

**Comment by darbyjohnston** [comment]
> I didn’t succeed in bringing back the translations to the new keys. So, many of the translated strings are broken… Maybe they’d just as soon be translated again from the new IDs? I don’t mind going over the French version once more, it needs it anyway. Were there other corrected languages?

I think that's fine, I will merge this and then re-run the machine translations. Once I have that checked in if you want to take a look at the French translations again that would be great. The only other translations that have been fixed up were for Spanish:

https://github.com/darbyjohnston/DJV/issues/182

I think there were relatively few changes though, so I'll try copying and pasting them into the new IDs.

> Oh, one day isn’t too long a delay! I’m not in a hurry, and I don’t feel entitled to press open source developers who may have other stuff to deal with. :)

No pressure at all, it's great to make some forward progress on this. Once this is wrapped up and the Weblate workflow is setup, a number of other open issues will be possible to resolve:

https://github.com/darbyjohnston/DJV/issues/205
https://github.com/darbyjohnston/DJV/issues/181
https://github.com/darbyjohnston/DJV/issues/166
https://github.com/darbyjohnston/DJV/issues/98

**Comment by darbyjohnston** [comment]
OK, I've merged the changes and re-run the machine translations; if you want go ahead and take a look at the French translations, or we could wait until the Weblate account is setup and use that as the first test of the new workflow.

I was also able to reapply most of the Spanish fixes, and fixed the missing translation functions. I also fixed up the translation scripts (extract.py/translate.py) so they work with the new .text files and also keep the contents sorted. So we are in pretty good shape now. :) Hopefully the Weblate account request comes through soon...

**Pull request merged**
